spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
endpoints:
  shutdown:
    enabled: true
# 环境变量
---
spring:
  profiles: dev
  application:
    name: api-gategory
server:
  context-path: /dev
  port: 8081
#  打印调试信息
debug: true
logging:
  config: classpath:logback-springboot.xml
---
spring:
  profiles: test
  application:
      name: api-gategory
server:
  context-path: /test
  port: 8082
---
spring:
  profiles: product
  application:
      name: api-gategory
server:
  context-path: /product
  port: 80